const fs = require('fs');
const path = require('path');
const readline = require('readline');

// In-memory fallback dataset so POLARIS is 100% operational even without a running local MongoDB instance
let mockBases = [
  {
    _id: '67cda0000000000000000001',
    name: 'Maitri Station',
    code: 'MAITRI',
    location: 'Schirmacher Oasis, Queen Maud Land, East Antarctica',
    coordinates: { lat: -70.767, lng: 11.733 },
    type: 'Permanent Station',
    capacity: 65,
    currentPersonnel: 38,
    status: 'Operational',
    operationalStatus: 'Operational',
    elevationMeters: 117,
    description: 'Year-round Indian Antarctic research station operating atmospheric, geological, and geomagnetic laboratories on freshwater Lake Priyadarshini oasis.',
    commsStatus: 'Optimal',
    weatherTelemetry: {
      temperature: -28.4,
      windSpeed: '24 kt',
      windGust: '38 kt',
      baroPressure: '982 hPa',
      condition: 'Freezing Fog',
      humidity: '71%',
      visibility: '6.5 km',
    },
    facilities: [
      'Deep Ice Coring Hangar',
      'Life Support Microgrid (CAT 3406)',
      'Atmospheric Dobson Ozone Lab',
      'Geomagnetic Field Array',
      'Primary Surgical Trauma Bay',
      'Hydroponics Crop Module Alpha',
    ],
  },
  {
    _id: '67cda0000000000000000002',
    name: 'Bharati Station',
    code: 'BHARATI',
    location: 'Larsemann Hills, East Antarctica',
    coordinates: { lat: -69.407, lng: 76.191 },
    type: 'Permanent Station',
    capacity: 72,
    currentPersonnel: 44,
    status: 'Operational',
    operationalStatus: 'Operational',
    elevationMeters: 35,
    description: 'State-of-the-art modular polar station with uninterrupted satellite links, oceanographic laboratories, and high-latitude wind turbine arrays.',
    commsStatus: 'Optimal',
    weatherTelemetry: {
      temperature: -18.2,
      windSpeed: '16 kt',
      windGust: '26 kt',
      baroPressure: '998 hPa',
      condition: 'Partly Cloudy',
      humidity: '58%',
      visibility: '18 km',
    },
    facilities: [
      'Cobham Ka-Band Satellite Terminal',
      'Wind Turbine Hybrid Farm (40 kW)',
      'Cryogenic Sample Vault (-80°C)',
      'Sub-Ice Coring Mast Assembly',
      'Autonomous UAV Sled Docking Bay',
      'Tele-Medicine Surgical Suite',
    ],
  },
  {
    _id: '67cda0000000000000000003',
    name: 'Himadri Station',
    code: 'HIMADRI',
    location: 'Ny-Ålesund, Spitsbergen, Svalbard (Arctic 79°N)',
    coordinates: { lat: 78.924, lng: 11.928 },
    type: 'Research Station',
    capacity: 25,
    currentPersonnel: 14,
    status: 'Operational',
    operationalStatus: 'Operational',
    elevationMeters: 15,
    description: 'Northernmost Indian Arctic station dedicated to aerosol chemistry, marine biology, and seasonal fjord glacial retreat studies.',
    commsStatus: 'Optimal',
    weatherTelemetry: {
      temperature: -6.5,
      windSpeed: '12 kt',
      windGust: '18 kt',
      baroPressure: '1014 hPa',
      condition: 'Light Flurries',
      humidity: '82%',
      visibility: '12 km',
    },
    facilities: [
      'Multi-Wavelength Optical Lidar',
      'Marine Biology Wet Labs',
      'Zeppelin Observatory Feed Link',
      'Snow Stratigraphy Clean Room',
      'Polar Bear Emergency Defense Locker',
    ],
  },
  {
    _id: '67cda0000000000000000004',
    name: 'RV Bharati',
    code: 'RV-BHARATI',
    location: 'Southern Ocean (Off Princess Astrid Coast)',
    coordinates: { lat: -65.2, lng: 45.3 },
    type: 'Mobile Vessel',
    capacity: 50,
    currentPersonnel: 28,
    status: 'Operational',
    operationalStatus: 'Operational',
    elevationMeters: 0,
    description: 'Heavy polar research and logistics resupply vessel navigating the Southern Ocean with deep-sea sonar, helicopter helideck, and container holds.',
    commsStatus: 'Optimal',
    weatherTelemetry: {
      temperature: -4.1,
      windSpeed: '32 kt',
      windGust: '46 kt',
      baroPressure: '974 hPa',
      condition: 'Heavy Swell & Sea Spray',
      humidity: '89%',
      visibility: '8 km',
    },
    facilities: [
      'Helideck & Mi-8 Cargo Sling Bay',
      'Multibeam Hydrographic Echo-Sounder',
      'Containerized Cryo-Hold #3',
      'Desalination Reverse Osmosis Plant',
      'Vessel Medical Infirmary',
    ],
  },
];

let mockUsers = [
  { _id: '67cda1000000000000000001', name: 'Commander Radhika Roy', email: 'admin@polaris.aq', role: 'SuperAdmin', isActive: true },
  { _id: '67cda1000000000000000002', name: 'Dr. Rajesh Sharma', email: 'expeditions@polaris.aq', role: 'ExpeditionManager', isActive: true },
  { _id: '67cda1000000000000000003', name: 'Ananya Sharma', email: 'logistics@polaris.aq', role: 'LogisticsCoordinator', isActive: true },
  { _id: '67cda1000000000000000004', name: 'Rohan Verma', email: 'inventory@polaris.aq', role: 'InventoryManager', isActive: true },
  { _id: '67cda1000000000000000005', name: 'Capt. Amitav Banerjee', email: 'base.maitri@polaris.aq', role: 'BaseOfficer', isActive: true },
  { _id: '67cda1000000000000000006', name: 'Dr. Maya Patel', email: 'medical@polaris.aq', role: 'MedicalOfficer', isActive: true },
  { _id: '67cda1000000000000000007', name: 'Priya Venkat', email: 'personnel@polaris.aq', role: 'PersonnelManager', isActive: true },
  { _id: '67cda1000000000000000008', name: 'Alok Mathur', email: 'viewer@polaris.aq', role: 'Viewer', isActive: true },
];

let mockExpeditions = [
  {
    _id: '67cda2000000000000000001',
    code: 'INAE-44',
    expeditionCode: 'INAE-44',
    name: '44th Indian Antarctic Expedition',
    type: 'Antarctic',
    baseName: 'Bharati Station',
    destinationBase: {
      _id: '67cda0000000000000000002',
      name: 'Bharati Station',
      code: 'BHARATI',
      location: 'Larsemann Hills, East Antarctica',
      coordinates: { lat: -69.407, lng: 76.191 }
    },
    leader: 'Dr. Rajesh Sharma',
    description: 'Premier Indian national research mission executing deep ice-core extraction, wind turbine grid commissioning, and cryosphere telemetry across Amery Ice Shelf.',
    status: 'Active',
    startDate: '2025-11-15T00:00:00.000Z',
    endDate: '2026-12-20T00:00:00.000Z',
    readinessScore: 87,
    riskLevel: 'Moderate',
    progress: 75,
    aiRiskPrediction: 'Low probability of delay. Weather window optimal for next 7 days.',
    objectives: [
      'Drill 120m ice core at Amery Ice Shelf for CO2 isotope modeling',
      'Commission 40kW arctic-grade wind turbine array at Bharati perimeter',
      'UAV laser bathymetry of fast-ice calving margin'
    ],
    budget: { allocated: 4500000, spent: 2850000 },
    assignedPersonnel: [
      {
        _id: '67cda6000000000000000001',
        name: 'Dr. Rajesh Sharma',
        designation: 'Lead Glaciologist',
        team: 'Science',
        department: 'Science',
        status: 'Deployed',
        medicalClearance: 'Cleared',
        emergencyContact: '+91-9876543210',
        skills: ['Ice Core Sampling', 'Cryosphere Modeling', 'Glacial Radar']
      },
      {
        _id: '67cda6000000000000000002',
        name: 'Dr. Maya Patel',
        designation: 'Chief Medical Officer',
        team: 'Medical',
        department: 'Medical',
        status: 'Deployed',
        medicalClearance: 'Cleared',
        emergencyContact: '+91-9876543211',
        skills: ['Hypothermia Protocol', 'Tele-Surgery', 'Frostbite Triage']
      },
      {
        _id: '67cda6000000000000000003',
        name: 'Pooja Deshmukh',
        designation: 'Logistics Flight Director',
        team: 'Logistics',
        department: 'Logistics',
        status: 'Deployed',
        medicalClearance: 'Cleared',
        emergencyContact: '+91-9876543214',
        skills: ['Air Delivery Drop', 'Cargo Manifest', 'Weather Windowing']
      },
      {
        _id: '67cda6000000000000000004',
        name: 'Vikram Sengupta',
        designation: 'Chief Electrical Engineer',
        team: 'Operations',
        department: 'Operations',
        status: 'Deployed',
        medicalClearance: 'Cleared',
        emergencyContact: '+91-9876543212',
        skills: ['Microgrid Synchronization', 'Cold-Start Generators', 'Turbines']
      }
    ],
    assignedResources: [
      {
        _id: '67cda5000000000000000001',
        item: 'PistenBully 300 Polar Snow Groomer (PB-01)',
        category: 'Vehicle',
        refModel: 'Asset',
        quantity: 2,
        notes: 'Equipped with heavy deep-snow track cleats and auxiliary cab heater.'
      },
      {
        _id: '67cda5000000000000000002',
        item: 'Thermal Electro-Mechanical Core Drill Assembly',
        category: 'Scientific Instrument',
        refModel: 'Asset',
        quantity: 1,
        notes: 'Rated to -55°C downhole ambient temperature.'
      },
      {
        _id: '67cda4000000000000000001',
        item: 'Aviation Turbine Fuel Jet A-1 Cryo Drums',
        category: 'Fuel',
        refModel: 'Inventory',
        quantity: 40,
        notes: 'Stored in freeze-resistant insulated pallets at Base Camp.'
      },
      {
        _id: '67cda4000000000000000003',
        item: 'Emergency Cryo Blood Plasma Units (O-Neg)',
        category: 'Medical',
        refModel: 'Inventory',
        quantity: 12,
        notes: 'Vacuum-sealed in mobile tactical trauma cryo-chest.'
      }
    ],
    milestones: [
      { _id: '67cdm1000000000000000001', title: 'Base Camp Setup & Satellite Lock', dueDate: '2025-12-01T00:00:00.000Z', status: 'Completed' },
      { _id: '67cdm1000000000000000002', title: 'Over-Ice Traverse to Amery Ridge Sector 4', dueDate: '2026-02-15T00:00:00.000Z', status: 'Completed' },
      { _id: '67cdm1000000000000000003', title: 'Subglacial Ice Core Extraction (120m Target)', dueDate: '2026-05-30T00:00:00.000Z', status: 'In Progress' },
      { _id: '67cdm1000000000000000004', title: 'Specimen Packaging & Return Traverse to Bharati', dueDate: '2026-11-15T00:00:00.000Z', status: 'Pending' }
    ],
    timeline: [
      { _id: 'log1', action: 'EXPEDITION_CREATED', description: 'Mission INAE-44 authorized and registered under POLARIS C2 Protocol.', actorName: 'Commander Radhika Roy', createdAt: '2025-10-12T08:00:00.000Z' },
      { _id: 'log2', action: 'PERSONNEL_ASSIGNED', description: 'Assigned Dr. Rajesh Sharma and 3 specialists to primary traverse roster.', actorName: 'Dr. Rajesh Sharma', createdAt: '2025-11-01T10:30:00.000Z' },
      { _id: 'log3', action: 'MILESTONE_COMPLETED', description: 'Milestone "Base Camp Setup & Satellite Lock" marked Completed.', actorName: 'Pooja Deshmukh', createdAt: '2025-12-01T14:15:00.000Z' },
      { _id: 'log4', action: 'MILESTONE_COMPLETED', description: 'Milestone "Over-Ice Traverse to Amery Ridge Sector 4" marked Completed.', actorName: 'Vikram Sengupta', createdAt: '2026-02-15T18:45:00.000Z' }
    ]
  },
  {
    _id: '67cda2000000000000000002',
    code: 'LARSEM-2026',
    expeditionCode: 'LARSEM-2026',
    name: 'Larsemann Hills Structural Bedrock Survey',
    type: 'Survey',
    baseName: 'Bharati Station',
    destinationBase: {
      _id: '67cda0000000000000000002',
      name: 'Bharati Station',
      code: 'BHARATI',
      location: 'Larsemann Hills, East Antarctica',
      coordinates: { lat: -69.407, lng: 76.191 }
    },
    leader: 'Capt. Amitav Banerjee',
    description: 'High-precision tectonic and geomagnetic bedrock mapping in the Larsemann Hills oasis using mobile broadband seismographs.',
    status: 'Active',
    startDate: '2026-01-10T00:00:00.000Z',
    endDate: '2026-12-31T00:00:00.000Z',
    readinessScore: 62,
    riskLevel: 'High',
    progress: 41,
    aiRiskPrediction: '74-knot gusts causing 3-day delay. Sheltering at Refuge Pod 3.',
    objectives: [
      'Sustain wintering team of 25 personnel at Refuge Pods',
      'Maintain ozone observation Dobson spectrophotometer',
      'Map bedrock fault lines across Fisher Island channel'
    ],
    budget: { allocated: 3800000, spent: 1900000 },
    assignedPersonnel: [
      {
        _id: '67cda6000000000000000005',
        name: 'Capt. Amitav Banerjee',
        designation: 'Station Base Commander',
        team: 'Command',
        department: 'Command',
        status: 'Deployed',
        medicalClearance: 'Cleared',
        emergencyContact: '+91-9876543215',
        skills: ['Ice Navigation', 'Hazard Mitigation', 'Gale Survival']
      }
    ],
    assignedResources: [
      {
        _id: '67cda5000000000000000003',
        item: 'Hägglunds BV206 All-Terrain Tracked Carrier',
        category: 'Vehicle',
        refModel: 'Asset',
        quantity: 1,
        notes: 'Winterized rubber tracks.'
      }
    ],
    milestones: [
      { _id: '67cdm2000000000000000001', title: 'Lake Pipeline Heat-Tracing Inspection', dueDate: '2026-02-01T00:00:00.000Z', status: 'Completed' },
      { _id: '67cdm2000000000000000002', title: 'Fuel Delivery Convoy from Coast', dueDate: '2026-03-05T00:00:00.000Z', status: 'In Progress' }
    ],
    timeline: [
      { _id: 'log5', action: 'EXPEDITION_CREATED', description: 'Survey mission initialized.', actorName: 'Commander Radhika Roy', createdAt: '2026-01-05T09:00:00.000Z' }
    ]
  },
  {
    _id: '67cda2000000000000000003',
    code: 'ARCTIC-2026',
    expeditionCode: 'ARCTIC-2026',
    name: 'Ny-Ålesund Spring Atmospheric Survey',
    type: 'Arctic',
    baseName: 'Himadri Station',
    destinationBase: {
      _id: '67cda0000000000000000003',
      name: 'Himadri Station',
      code: 'HIMADRI',
      location: 'Ny-Ålesund, Svalbard',
      coordinates: { lat: 78.924, lng: 11.928 }
    },
    leader: 'Dr. Sunita Rao',
    description: 'Svalbard optical lidar profiling of spring aerosol nucleation and black carbon deposition during arctic sunrise.',
    status: 'Planning',
    startDate: '2026-04-01T00:00:00.000Z',
    endDate: '2026-09-30T00:00:00.000Z',
    readinessScore: 45,
    riskLevel: 'Low',
    progress: 0,
    aiRiskPrediction: 'Awaiting sensor bench calibration. No environmental risks.',
    objectives: [
      'Deploy multi-wavelength micro-pulse lidar at Zeppelin Observatory',
      'Quantify organic aerosols during seasonal snow melt'
    ],
    budget: { allocated: 1200000, spent: 180000 },
    assignedPersonnel: [],
    assignedResources: [],
    milestones: [
      { _id: '67cdm3000000000000000001', title: 'Sensor Bench Calibration & Bench Test', dueDate: '2026-03-20T00:00:00.000Z', status: 'In Progress' }
    ],
    timeline: [
      { _id: 'log6', action: 'EXPEDITION_CREATED', description: 'Arctic campaign registered for Q2 2026 deployment.', actorName: 'Dr. Rajesh Sharma', createdAt: '2026-02-01T11:00:00.000Z' }
    ]
  },
  {
    _id: '67cda2000000000000000004',
    code: 'RESUP-26',
    expeditionCode: 'RESUP-26',
    name: 'Bharati Resupply Convoy',
    type: 'Resupply',
    baseName: 'Bharati Station',
    destinationBase: {
      _id: '67cda0000000000000000002',
      name: 'Bharati Station',
      code: 'BHARATI',
      location: 'Larsemann Hills, East Antarctica',
      coordinates: { lat: -69.407, lng: 76.191 }
    },
    leader: 'Pooja Deshmukh',
    description: 'Critical annual over-ice fuel convoy and heavy machinery transfer from Princess Astrid Coast to station fuel bladders.',
    status: 'Active',
    startDate: '2026-02-01T00:00:00.000Z',
    endDate: '2026-03-15T00:00:00.000Z',
    readinessScore: 94,
    riskLevel: 'Low',
    progress: 92,
    aiRiskPrediction: 'Clear corridor. Docking expected in 2h 15m.',
    objectives: [
      'Transport 40,000L polar diesel to Main Bladder',
      'Deliver replacement CAT 3406 generator alternator'
    ],
    budget: { allocated: 800000, spent: 650000 },
    assignedPersonnel: [],
    assignedResources: [],
    milestones: [
      { _id: '67cdm4000000000000000001', title: 'Depart Coast Landing Bay', dueDate: '2026-02-02T00:00:00.000Z', status: 'Completed' },
      { _id: '67cdm4000000000000000002', title: 'Arrival at Bharati Station Perimeter', dueDate: '2026-03-10T00:00:00.000Z', status: 'In Progress' }
    ],
    timeline: [
      { _id: 'log7', action: 'EXPEDITION_CREATED', description: 'Resupply convoy cleared by Maritime Command.', actorName: 'Pooja Deshmukh', createdAt: '2026-01-20T10:00:00.000Z' }
    ]
  },
];

let mockCargo = [
  {
    _id: '67cda3000000000000000001',
    cargoCode: 'CRG-2026-001',
    trackingNumber: 'CRG-2026-001',
    description: 'Emergency Aviation Turbine Fuel Resupply (Jet A-1)',
    title: 'Emergency Aviation Turbine Fuel Resupply (Jet A-1)',
    name: 'Emergency Aviation Turbine Fuel Resupply (Jet A-1)',
    category: 'Fuel',
    origin: 'Cape Town Port',
    destination: 'Maitri Base',
    destinationBaseName: 'Maitri Station',
    currentLocation: 'Southern Ocean (Lat -64.5°, Lng 22.0°)',
    currentCoordinates: { lat: -64.5, lng: 22.0 },
    routeCoordinates: [
      { lat: -33.92, lng: 18.42 }, // Cape Town
      { lat: -50.0, lng: 20.0 },
      { lat: -64.5, lng: 22.0 }, // Current vessel pos
      { lat: -70.767, lng: 11.733 }, // Maitri Station
    ],
    carrier: 'RV Vasiliy Golovnin Icebreaker',
    status: 'In Transit',
    priority: 'Urgent',
    weightKg: 4200,
    volumeM3: 6.5,
    quantity: 20,
    eta: '3 Days (15 Sep 2026)',
    expectedArrival: '2026-09-15T18:00:00.000Z',
    barcodeValue: 'POLARIS-CRG-2026-001-JET-A1',
    temperatureRequirement: 'Cryo-Heated (-10°C to +5°C)',
    currentTemperature: -4.2,
    batteryReserve: 96,
    shockGForce: 0.4,
    items: [
      { _id: 'ci-01', name: 'Jet A-1 Polar Grade Fuel Drums', quantity: 20, unit: 'Drums' },
    ],
    trackingHistory: [
      {
        _id: 'th-01-1',
        status: 'Planned',
        location: 'Cape Town Logistics Hub',
        timestamp: '2026-09-01T08:00:00.000Z',
        updatedByName: 'Lt. Rohan Verma',
        notes: 'Emergency manifest authorized by Polar Air Ops Command',
      },
      {
        _id: 'th-01-2',
        status: 'Packed',
        location: 'Cape Town Pier 4',
        timestamp: '2026-09-04T12:30:00.000Z',
        updatedByName: 'Pooja Deshmukh',
        notes: 'Loaded into insulated sub-zero sea container #C-904',
      },
      {
        _id: 'th-01-3',
        status: 'In Transit',
        location: 'Southern Ocean Waypoint Alpha-2',
        timestamp: '2026-09-08T06:00:00.000Z',
        updatedByName: 'Capt. Amitav Banerjee',
        notes: 'Vessel proceeding at 13.8 knots. Ice conditions moderate.',
      },
    ],
  },
  {
    _id: '67cda3000000000000000002',
    cargoCode: 'CRG-2026-002',
    trackingNumber: 'CRG-2026-002',
    description: 'Caterpillar 3406 Crankshaft & Prime Alternator Overhaul Kit',
    title: 'Caterpillar 3406 Crankshaft & Prime Alternator Overhaul Kit',
    name: 'Caterpillar 3406 Crankshaft & Prime Alternator Overhaul Kit',
    category: 'Equipment',
    origin: 'Bremerhaven Port',
    destination: 'Maitri Base',
    destinationBaseName: 'Maitri Station',
    currentLocation: 'Cape Darnley Refuge Hangar (Delayed)',
    currentCoordinates: { lat: -67.5, lng: 30.2 },
    routeCoordinates: [
      { lat: 53.54, lng: 8.58 }, // Bremerhaven
      { lat: -33.92, lng: 18.42 }, // Cape Town
      { lat: -67.5, lng: 30.2 }, // Cape Darnley
      { lat: -70.767, lng: 11.733 }, // Maitri
    ],
    carrier: 'Mil Mi-8 Polar Heavy Lift Sling',
    status: 'Delayed',
    priority: 'Critical',
    weightKg: 850,
    volumeM3: 2.2,
    quantity: 2,
    eta: 'Pending Weather Window (+48h)',
    expectedArrival: '2026-09-18T12:00:00.000Z',
    barcodeValue: 'POLARIS-CRG-2026-002-CAT-CRANK',
    temperatureRequirement: 'Standard Ambient (Dry)',
    currentTemperature: -18.6,
    batteryReserve: 88,
    shockGForce: 1.1,
    items: [
      { _id: 'ci-02', name: 'CAT 3406 Marine Crankshaft', quantity: 1, unit: 'Unit' },
      { _id: 'ci-03', name: 'High-Tensile Heat-Shield Gaskets', quantity: 1, unit: 'Set' },
    ],
    trackingHistory: [
      {
        _id: 'th-02-1',
        status: 'Planned',
        location: 'Bremerhaven Depot',
        timestamp: '2026-08-20T10:00:00.000Z',
        updatedByName: 'Engineering HQ',
        notes: 'Priority generator spare release',
      },
      {
        _id: 'th-02-2',
        status: 'In Transit',
        location: 'Helicopter Air-Lift Staging',
        timestamp: '2026-09-05T14:00:00.000Z',
        updatedByName: 'Flight Director Pooja Deshmukh',
        notes: 'Air transit underway from coastal ice pier',
      },
      {
        _id: 'th-02-3',
        status: 'Delayed',
        location: 'Cape Darnley Refuge Pod',
        timestamp: '2026-09-11T16:45:00.000Z',
        updatedByName: 'Flight Director Pooja Deshmukh',
        notes: '65-knot gale blizzard warning. Helicopter grounded for safety.',
      },
    ],
  },
  {
    _id: '67cda3000000000000000003',
    cargoCode: 'CRG-2026-003',
    trackingNumber: 'CRG-2026-003',
    description: 'Deep Amery Ice Shelf Core Samples (Cryo-Preserved -80°C)',
    title: 'Deep Amery Ice Shelf Core Samples (Cryo-Preserved -80°C)',
    name: 'Deep Amery Ice Shelf Core Samples (Cryo-Preserved -80°C)',
    category: 'Scientific',
    origin: 'Bharati Station',
    destination: 'RV Bharati Icebreaker',
    destinationBaseName: 'RV Bharati',
    currentLocation: 'Prydz Bay Fast-Ice Traverse',
    currentCoordinates: { lat: -68.8, lng: 74.5 },
    routeCoordinates: [
      { lat: -69.407, lng: 76.191 }, // Bharati
      { lat: -68.8, lng: 74.5 }, // Prydz Bay
      { lat: -65.2, lng: 45.3 }, // RV Bharati
    ],
    carrier: 'Kässbohrer PB300 Cryo-Sled Convoy',
    status: 'In Transit',
    priority: 'High',
    weightKg: 320,
    volumeM3: 1.5,
    quantity: 4,
    eta: 'Tomorrow, 08:30 UTC',
    expectedArrival: '2026-09-13T08:30:00.000Z',
    barcodeValue: 'POLARIS-CRG-2026-003-ICE-CORE-80C',
    temperatureRequirement: 'Ultra-Low Cryogenic (-80°C)',
    currentTemperature: -82.4,
    batteryReserve: 94,
    shockGForce: 0.2,
    items: [
      { _id: 'ci-04', name: 'Cryo Core Sample Cylinders (120m depth)', quantity: 4, unit: 'Vessels' },
    ],
    trackingHistory: [
      {
        _id: 'th-03-1',
        status: 'Packed',
        location: 'Bharati Deep Glaciology Lab',
        timestamp: '2026-09-08T09:00:00.000Z',
        updatedByName: 'Dr. Rajesh Sharma',
        notes: 'Sealed inside vacuum liquid nitrogen shippers',
      },
      {
        _id: 'th-03-2',
        status: 'In Transit',
        location: 'Prydz Bay Sea-Ice Waypoint 3',
        timestamp: '2026-09-11T18:00:00.000Z',
        updatedByName: 'Arjun Nair',
        notes: 'Traverse moving at 12 km/h across fast-ice corridor',
      },
    ],
  },
  {
    _id: '67cda3000000000000000004',
    cargoCode: 'CRG-2026-004',
    trackingNumber: 'CRG-2026-004',
    description: 'High-Calorie Polar Trekking MREs & Freeze-Dried Rations',
    title: 'High-Calorie Polar Trekking MREs & Freeze-Dried Rations',
    name: 'High-Calorie Polar Trekking MREs & Freeze-Dried Rations',
    category: 'Provisions',
    origin: 'Cape Town Port',
    destination: 'Bharati Base',
    destinationBaseName: 'Bharati Station',
    currentLocation: 'Bharati Station Food Store Modular Bay 4',
    currentCoordinates: { lat: -69.407, lng: 76.191 },
    routeCoordinates: [
      { lat: -33.92, lng: 18.42 }, // Cape Town
      { lat: -60.0, lng: 55.0 },
      { lat: -69.407, lng: 76.191 }, // Bharati Station
    ],
    carrier: 'MV Vasiliy Golovnin',
    status: 'Delivered',
    priority: 'Standard',
    weightKg: 2800,
    volumeM3: 5.4,
    quantity: 1420,
    eta: 'Delivered & Cataloged',
    expectedArrival: '2026-09-01T17:00:00.000Z',
    barcodeValue: 'POLARIS-CRG-2026-004-RATIONS-MRE',
    temperatureRequirement: 'Cool Dry Ambient (+5°C to +15°C)',
    currentTemperature: 8.5,
    batteryReserve: 100,
    shockGForce: 0.1,
    items: [
      { _id: 'ci-05', name: '4500 kcal Polar Ration Packs', quantity: 1420, unit: 'Packs' },
    ],
    trackingHistory: [
      {
        _id: 'th-04-1',
        status: 'Dispatched',
        location: 'Cape Town Berth 12',
        timestamp: '2026-08-15T10:00:00.000Z',
        updatedByName: 'Port Agent',
        notes: 'Vessel departure confirmed',
      },
      {
        _id: 'th-04-2',
        status: 'In Transit',
        location: 'Southern Indian Ocean',
        timestamp: '2026-08-24T14:00:00.000Z',
        updatedByName: 'Capt. Manpreet Singh',
        notes: 'Crossing Antarctic Convergence 60°S',
      },
      {
        _id: 'th-04-3',
        status: 'Delivered',
        location: 'Bharati Station Pantry',
        timestamp: '2026-09-01T17:00:00.000Z',
        updatedByName: 'Quartermaster Rohan Verma',
        notes: 'Manifest fully inspected and placed in dry storage',
      },
    ],
  },
  {
    _id: '67cda3000000000000000005',
    cargoCode: 'CRG-2026-005',
    trackingNumber: 'CRG-2026-005',
    description: 'PistenBully 300 Heavy Cleat Tracks & Hydraulic Pumps',
    title: 'PistenBully 300 Heavy Cleat Tracks & Hydraulic Pumps',
    name: 'PistenBully 300 Heavy Cleat Tracks & Hydraulic Pumps',
    category: 'Equipment',
    origin: 'Bremerhaven Port',
    destination: 'Maitri Base',
    destinationBaseName: 'Maitri Station',
    currentLocation: 'Sub-Ice Traverse Corridor Beta',
    currentCoordinates: { lat: -70.4, lng: 14.2 },
    routeCoordinates: [
      { lat: -33.92, lng: 18.42 }, // Cape Town
      { lat: -69.0, lng: 12.0 },
      { lat: -70.4, lng: 14.2 }, // Current
      { lat: -70.767, lng: 11.733 }, // Maitri
    ],
    carrier: 'Bv206 Sled Convoy Unit 2',
    status: 'In Transit',
    priority: 'Medium',
    weightKg: 1250,
    volumeM3: 3.1,
    quantity: 6,
    eta: '1 Day (13 Sep 2026)',
    expectedArrival: '2026-09-13T22:00:00.000Z',
    barcodeValue: 'POLARIS-CRG-2026-005-PB-TRACKS',
    temperatureRequirement: 'Standard Ambient',
    currentTemperature: -24.1,
    batteryReserve: 91,
    shockGForce: 0.8,
    items: [
      { _id: 'ci-06', name: 'High-Tensile Steel Cleats', quantity: 16, unit: 'Pieces' },
      { _id: 'ci-07', name: 'Rexroth Hydraulic Drive Pump', quantity: 2, unit: 'Units' },
    ],
    trackingHistory: [
      {
        _id: 'th-05-1',
        status: 'Packed',
        location: 'Princess Astrid Coast Ice Pier',
        timestamp: '2026-09-09T08:00:00.000Z',
        updatedByName: 'Arjun Nair',
        notes: 'Secured to heavy-duty polar steel freight sledge',
      },
      {
        _id: 'th-05-2',
        status: 'In Transit',
        location: 'Waypoint Schirmacher Oasis Gate',
        timestamp: '2026-09-11T12:00:00.000Z',
        updatedByName: 'Convoy Lead Amitav Banerjee',
        notes: 'Approaching oasis perimeter ridge',
      },
    ],
  },
  {
    _id: '67cda3000000000000000006',
    cargoCode: 'CRG-2026-006',
    trackingNumber: 'CRG-2026-006',
    description: 'Emergency Blood Plasma Vault & Tele-Surgery Response Bay',
    title: 'Emergency Blood Plasma Vault & Tele-Surgery Response Bay',
    name: 'Emergency Blood Plasma Vault & Tele-Surgery Response Bay',
    category: 'Medical',
    origin: 'Goa Medical Depot',
    destination: 'Himadri Station',
    destinationBaseName: 'Himadri Station',
    currentLocation: 'Longyearbyen Svalbard Airport Staging',
    currentCoordinates: { lat: 78.22, lng: 15.65 },
    routeCoordinates: [
      { lat: 15.49, lng: 73.82 }, // Goa
      { lat: 59.91, lng: 10.75 }, // Oslo
      { lat: 78.22, lng: 15.65 }, // Longyearbyen
      { lat: 78.92, lng: 11.93 }, // Himadri
    ],
    carrier: 'Scandinavian Air Freight Flight SK-914',
    status: 'Planned',
    priority: 'High',
    weightKg: 180,
    volumeM3: 0.9,
    quantity: 12,
    eta: '4 Days (16 Sep 2026)',
    expectedArrival: '2026-09-16T14:00:00.000Z',
    barcodeValue: 'POLARIS-CRG-2026-006-MED-PLASMA',
    temperatureRequirement: 'Cryo Deep Frozen (-40°C)',
    currentTemperature: -38.5,
    batteryReserve: 98,
    shockGForce: 0.1,
    items: [
      { _id: 'ci-08', name: 'O-Negative Plasma Packs', quantity: 12, unit: 'Packs' },
      { _id: 'ci-09', name: 'Tele-Surgery Suture Robotic End', quantity: 2, unit: 'Units' },
    ],
    trackingHistory: [
      {
        _id: 'th-06-1',
        status: 'Planned',
        location: 'Goa National Centre for Polar Research',
        timestamp: '2026-09-07T11:00:00.000Z',
        updatedByName: 'Dr. Maya Patel',
        notes: 'Priority clinical medical dispatch authorized',
      },
      {
        _id: 'th-06-2',
        status: 'Packed',
        location: 'Longyearbyen Svalbard Hangar',
        timestamp: '2026-09-10T15:00:00.000Z',
        updatedByName: 'Station Logistics Tech Sunita Rao',
        notes: 'Awaiting helicopter weather clearance across Kongsfjorden',
      },
    ],
  },
  {
    _id: '67cda3000000000000000007',
    cargoCode: 'CRG-2026-007',
    trackingNumber: 'CRG-2026-007',
    description: 'Cobham Ka-Band Satellite Earth Terminal Radome Assembly',
    title: 'Cobham Ka-Band Satellite Earth Terminal Radome Assembly',
    name: 'Cobham Ka-Band Satellite Earth Terminal Radome Assembly',
    category: 'Communication',
    origin: 'Tromsø Polar Station',
    destination: 'Himadri Station',
    destinationBaseName: 'Himadri Station',
    currentLocation: 'Himadri Station Technical Hangar',
    currentCoordinates: { lat: 78.92, lng: 11.93 },
    routeCoordinates: [
      { lat: 69.65, lng: 18.96 }, // Tromso
      { lat: 78.22, lng: 15.65 }, // Longyearbyen
      { lat: 78.92, lng: 11.93 }, // Himadri
    ],
    carrier: 'Polaris Arctic Supply Vessel',
    status: 'At Base',
    priority: 'High',
    weightKg: 650,
    volumeM3: 3.8,
    quantity: 1,
    eta: 'Staged at Outpost Hangar',
    expectedArrival: '2026-09-10T12:00:00.000Z',
    barcodeValue: 'POLARIS-CRG-2026-007-SATCOM-RADOME',
    temperatureRequirement: 'Standard Ambient',
    currentTemperature: 4.2,
    batteryReserve: 100,
    shockGForce: 0.3,
    items: [
      { _id: 'ci-10', name: 'Heated Radome Carbon Fiber Housing', quantity: 1, unit: 'Unit' },
    ],
    trackingHistory: [
      {
        _id: 'th-07-1',
        status: 'Dispatched',
        location: 'Tromsø Harbor',
        timestamp: '2026-09-02T08:00:00.000Z',
        updatedByName: 'Tromsø Port Officer',
        notes: 'Vessel departure',
      },
      {
        _id: 'th-07-2',
        status: 'At Base',
        location: 'Himadri Station Perimeter',
        timestamp: '2026-09-10T12:00:00.000Z',
        updatedByName: 'Devendra Pratap',
        notes: 'Offloaded to technical hangar. Hoist scheduled for Saturday.',
      },
    ],
  },
  {
    _id: '67cda3000000000000000008',
    cargoCode: 'CRG-2026-008',
    trackingNumber: 'CRG-2026-008',
    description: 'Dobson Ozone Spectrophotometer Precision Calibration Cells',
    title: 'Dobson Ozone Spectrophotometer Precision Calibration Cells',
    name: 'Dobson Ozone Spectrophotometer Precision Calibration Cells',
    category: 'Scientific',
    origin: 'Christchurch Logistics Depot',
    destination: 'Bharati Station',
    destinationBaseName: 'Bharati Station',
    currentLocation: 'McMurdo Air Staging Strip',
    currentCoordinates: { lat: -77.85, lng: 166.66 },
    routeCoordinates: [
      { lat: -43.53, lng: 172.63 }, // Christchurch
      { lat: -77.85, lng: 166.66 }, // McMurdo
      { lat: -69.407, lng: 76.191 }, // Bharati
    ],
    carrier: 'USAF LC-130 Hercules Ski-Plane',
    status: 'In Transit',
    priority: 'Urgent',
    weightKg: 95,
    volumeM3: 0.6,
    quantity: 3,
    eta: '2 Days (14 Sep 2026)',
    expectedArrival: '2026-09-14T19:00:00.000Z',
    barcodeValue: 'POLARIS-CRG-2026-008-DOBSON-CELLS',
    temperatureRequirement: 'Shock-Isolated & Temperature Monitored',
    currentTemperature: -5.0,
    batteryReserve: 92,
    shockGForce: 0.1,
    items: [
      { _id: 'ci-11', name: 'Quartz Optical Absorption Cells', quantity: 3, unit: 'Vials' },
    ],
    trackingHistory: [
      {
        _id: 'th-08-1',
        status: 'Packed',
        location: 'Christchurch Antarctic Centre',
        timestamp: '2026-09-06T09:00:00.000Z',
        updatedByName: 'Dr. Sunita Rao',
        notes: 'Laser calibrated and packed into shock-absorbent foam vault',
      },
      {
        _id: 'th-08-2',
        status: 'In Transit',
        location: 'McMurdo Air Runway',
        timestamp: '2026-09-11T14:30:00.000Z',
        updatedByName: 'Ski-Plane Flight Crew',
        notes: 'Inter-station air courier transfer leg initiated',
      },
    ],
  },
];


let mockInventory = [
  {
    _id: '67cda4000000000000000001',
    itemCode: 'ITM-001',
    sku: 'FUEL-JET-A1-01',
    itemName: 'Aviation Turbine Fuel (Jet A-1 Polar Grade)',
    name: 'Aviation Turbine Fuel (Jet A-1 Polar Grade)',
    category: 'Consumables & Fuel',
    baseName: 'Maitri Station',
    locationDetails: 'Bunker Tank Alpha-3 (Heated)',
    quantity: 2400,
    maxCapacity: 10000,
    unit: 'Liters',
    minThreshold: 5000,
    unitCost: 4.8,
    status: 'Low Stock',
    lastRestocked: '2026-02-15T12:00:00.000Z',
    movementHistory: [
      {
        _id: 'mv-inv-001',
        type: 'Addition',
        quantity: 5000,
        fromBaseName: 'Cape Town Vessel Offload',
        toBaseName: 'Maitri Station',
        performedByName: 'Rohan Verma',
        notes: 'Annual resupply transfer from MV Vasiliy Golovnin',
        timestamp: '2026-01-14T09:30:00.000Z',
      },
      {
        _id: 'mv-inv-002',
        type: 'Consumption',
        quantity: 2600,
        fromBaseName: 'Maitri Station',
        performedByName: 'Flight Ops Pooja Deshmukh',
        notes: 'Twin Otter Basler BT-67 aerial survey fuel top-up',
        timestamp: '2026-02-28T16:45:00.000Z',
      },
    ],
  },
  {
    _id: '67cda4000000000000000002',
    itemCode: 'ITM-002',
    sku: 'FUEL-DSL-45-02',
    itemName: 'Arctic Heavy Diesel (Pour Point -45°C)',
    name: 'Arctic Heavy Diesel (Pour Point -45°C)',
    category: 'Consumables & Fuel',
    baseName: 'Maitri Station',
    locationDetails: 'Main Fuel Bladder 1 & 2',
    quantity: 18500,
    maxCapacity: 30000,
    unit: 'Liters',
    minThreshold: 8000,
    unitCost: 3.2,
    status: 'In Stock',
    lastRestocked: '2026-02-01T08:00:00.000Z',
    movementHistory: [
      {
        _id: 'mv-inv-003',
        type: 'Addition',
        quantity: 20000,
        fromBaseName: 'Ice Shelf Traverse Convoy',
        toBaseName: 'Maitri Station',
        performedByName: 'Arjun Nair',
        notes: 'Bulk winter fuel depot fill',
        timestamp: '2026-01-20T11:00:00.000Z',
      },
    ],
  },
  {
    _id: '67cda4000000000000000003',
    itemCode: 'ITM-003',
    sku: 'MED-PLASMA-01',
    itemName: 'Emergency Blood Plasma Units (O-Neg & AB+)',
    name: 'Emergency Blood Plasma Units (O-Neg & AB+)',
    category: 'Medical & Trauma Kits',
    baseName: 'Bharati Station',
    locationDetails: 'Infirmary Cryo-Vault Bay 1',
    quantity: 12,
    maxCapacity: 50,
    unit: 'Packs',
    minThreshold: 20,
    unitCost: 320.0,
    status: 'Low Stock',
    expiryDate: '2027-01-01T00:00:00.000Z',
    lastRestocked: '2025-12-10T14:00:00.000Z',
    movementHistory: [
      {
        _id: 'mv-inv-004',
        type: 'Consumption',
        quantity: 3,
        fromBaseName: 'Bharati Station',
        performedByName: 'Dr. Maya Patel',
        notes: 'Crevasse rescue medical trauma stabilization',
        timestamp: '2026-02-18T18:15:00.000Z',
      },
    ],
  },
  {
    _id: '67cda4000000000000000004',
    itemCode: 'ITM-004',
    sku: 'FOOD-MRE-01',
    itemName: 'High-Calorie Polar Trekking MREs (4500 kcal)',
    name: 'High-Calorie Polar Trekking MREs (4500 kcal)',
    category: 'Rations',
    baseName: 'Bharati Station',
    locationDetails: 'Food Store Modular Bay 4',
    quantity: 1420,
    maxCapacity: 2500,
    unit: 'Packs',
    minThreshold: 400,
    unitCost: 18.5,
    status: 'In Stock',
    lastRestocked: '2026-01-05T10:00:00.000Z',
    movementHistory: [],
  },
  {
    _id: '67cda4000000000000000005',
    itemCode: 'ITM-005',
    sku: 'PART-PST-TRK-01',
    itemName: 'PistenBully 300 Steel-Climbing Track Cleats',
    name: 'PistenBully 300 Steel-Climbing Track Cleats',
    category: 'Heavy Machinery & Power',
    baseName: 'Bharati Station',
    locationDetails: 'Workshop Hangar Shelf G',
    quantity: 16,
    maxCapacity: 40,
    unit: 'Units',
    minThreshold: 8,
    unitCost: 650.0,
    status: 'In Stock',
    lastRestocked: '2026-01-12T14:00:00.000Z',
    movementHistory: [],
  },
  {
    _id: '67cda4000000000000000006',
    itemCode: 'ITM-006',
    sku: 'MED-FRST-03',
    itemName: 'Advanced Hypothermia & Frostbite Treatment Kits',
    name: 'Advanced Hypothermia & Frostbite Treatment Kits',
    category: 'Medical & Trauma Kits',
    baseName: 'Maitri Station',
    locationDetails: 'Trauma Bay 2 / Emergency Lockbox',
    quantity: 5,
    maxCapacity: 25,
    unit: 'Kits',
    minThreshold: 10,
    unitCost: 240.0,
    status: 'Critical',
    lastRestocked: '2025-11-20T09:00:00.000Z',
    movementHistory: [],
  },
  {
    _id: '67cda4000000000000000007',
    itemCode: 'ITM-007',
    sku: 'COM-SAT-IRID-01',
    itemName: 'Iridium Extreme Tactical Satellite Handsets',
    name: 'Iridium Extreme Tactical Satellite Handsets',
    category: 'Communications & Uplinks',
    baseName: 'Himadri Station',
    locationDetails: 'Radio Room Vault A',
    quantity: 6,
    maxCapacity: 12,
    unit: 'Units',
    minThreshold: 4,
    unitCost: 1450.0,
    status: 'In Stock',
    lastRestocked: '2026-02-10T11:00:00.000Z',
    movementHistory: [],
  },
  {
    _id: '67cda4000000000000000008',
    itemCode: 'ITM-008',
    sku: 'SCI-DRILL-COR-01',
    itemName: 'Sub-Ice Tungsten Carbide Coring Drill Bits',
    name: 'Sub-Ice Tungsten Carbide Coring Drill Bits',
    category: 'Scientific Instrumentation',
    baseName: 'Bharati Station',
    locationDetails: 'Deep Drilling Lab Container 3',
    quantity: 3,
    maxCapacity: 10,
    unit: 'Bits',
    minThreshold: 4,
    unitCost: 2800.0,
    status: 'Low Stock',
    lastRestocked: '2026-01-08T15:30:00.000Z',
    movementHistory: [],
  },
  {
    _id: '67cda4000000000000000009',
    itemCode: 'ITM-009',
    sku: 'FUEL-LPG-CYL-03',
    itemName: 'Low-Freeze Liquified Propane Cryo-Cylinders',
    name: 'Low-Freeze Liquified Propane Cryo-Cylinders',
    category: 'Consumables & Fuel',
    baseName: 'Larsemann Depot',
    locationDetails: 'External Cryo Rack Bay B',
    quantity: 18,
    maxCapacity: 60,
    unit: 'Cylinders',
    minThreshold: 20,
    unitCost: 180.0,
    status: 'Low Stock',
    lastRestocked: '2026-01-22T10:00:00.000Z',
    movementHistory: [],
  },
  {
    _id: '67cda4000000000000000010',
    itemCode: 'ITM-010',
    sku: 'GEAR-PARKA-01',
    itemName: 'Polar Extreme Goose Down Parkas (-60°C Rated)',
    name: 'Polar Extreme Goose Down Parkas (-60°C Rated)',
    category: 'Safety',
    baseName: 'RV Bharati',
    locationDetails: 'Vessel Quartermaster Locker Wing',
    quantity: 34,
    maxCapacity: 50,
    unit: 'Pieces',
    minThreshold: 15,
    unitCost: 850.0,
    status: 'In Stock',
    lastRestocked: '2026-01-02T08:00:00.000Z',
    movementHistory: [],
  },
];

let mockAssets = [
  {
    _id: '67cda5000000000000000001',
    assetCode: 'AST-0001',
    assetTag: 'AST-VEH-01',
    name: 'PistenBully 300 Polar Snow Groomer',
    assetName: 'PistenBully 300 Polar Snow Groomer',
    category: 'Vehicle',
    baseName: 'Bharati Station',
    model: 'Kässbohrer PB300 Polar',
    serialNumber: 'PB-2023-88741',
    assignedPersonnelName: 'Arjun Nair',
    condition: 'Good',
    status: 'Operational',
    maintenanceStatus: 'Up to Date',
    nextMaintenanceDate: '2026-05-15T00:00:00.000Z',
    lastMaintenanceDate: '2026-01-10T00:00:00.000Z',
    maintenanceIntervalDays: 90,
    specifications: {
      engine: 'Cummins QSC 8.3L Turbocharged',
      power: '330 HP',
      tracks: 'All-Steel Ice Climbing Cleats',
      maxSpeed: '24 km/h sub-zero',
    },
    maintenanceHistory: [
      {
        _id: 'mnt-001',
        date: '2026-01-10T10:00:00.000Z',
        type: 'Routine',
        notes: '90-day cold cycle fluid flush and track tension calibration',
        performedBy: 'Arjun Nair',
        cost: 450,
      },
    ],
  },
  {
    _id: '67cda5000000000000000002',
    assetCode: 'AST-0002',
    assetTag: 'AST-PWR-01',
    name: 'Station Prime Heat-Grid Generator #1',
    assetName: 'Station Prime Heat-Grid Generator #1',
    category: 'PowerGenerator',
    baseName: 'Maitri Station',
    model: 'Caterpillar 3406 DITA Arctic Pack',
    serialNumber: 'CAT-3406-9921',
    assignedPersonnelName: 'Vikram Sengupta',
    condition: 'Fair',
    status: 'Under Maintenance',
    maintenanceStatus: 'In Maintenance',
    nextMaintenanceDate: '2026-03-01T00:00:00.000Z',
    lastMaintenanceDate: '2025-11-25T00:00:00.000Z',
    maintenanceIntervalDays: 60,
    specifications: {
      powerOutput: '250 kVA / 400V 3-Phase',
      fuelType: 'Arctic Polar Diesel',
      runHours: '14,280 hrs',
      redundancy: 'Tier-1 Life-Support Critical',
    },
    maintenanceHistory: [
      {
        _id: 'mnt-002',
        date: '2026-02-28T14:30:00.000Z',
        type: 'Repair',
        notes: 'Replacing high-pressure injector nozzles and vibration dampers',
        performedBy: 'Vikram Sengupta',
        cost: 1200,
      },
    ],
  },
  {
    _id: '67cda5000000000000000003',
    assetCode: 'AST-0003',
    assetTag: 'AST-VEH-02',
    name: 'Hägglunds Bv206 All-Terrain Tracked Carrier',
    assetName: 'Hägglunds Bv206 All-Terrain Tracked Carrier',
    category: 'Vehicle',
    baseName: 'Maitri Station',
    model: 'BAE Systems Bv206 Twin-Cab',
    serialNumber: 'BV-982-1044',
    assignedPersonnelName: 'Capt. Amitav Banerjee',
    condition: 'Good',
    status: 'Operational',
    maintenanceStatus: 'Up to Date',
    nextMaintenanceDate: '2026-06-10T00:00:00.000Z',
    lastMaintenanceDate: '2026-02-05T00:00:00.000Z',
    maintenanceIntervalDays: 120,
    specifications: {
      seating: '17 personnel or 2,250 kg cargo',
      propulsion: 'Twin rubber tracks (amphibious snow/slush rated)',
      groundPressure: '13.8 kPa',
    },
    maintenanceHistory: [
      {
        _id: 'mnt-003',
        date: '2026-02-05T09:00:00.000Z',
        type: 'Inspection',
        notes: 'Pre-winter crevasse radar hitch inspection and cabin heater check',
        performedBy: 'Arjun Nair',
        cost: 300,
      },
    ],
  },
  {
    _id: '67cda5000000000000000004',
    assetCode: 'AST-0004',
    assetTag: 'AST-COM-01',
    name: 'High-Latitude C-Band Satellite Earth Terminal',
    assetName: 'High-Latitude C-Band Satellite Earth Terminal',
    category: 'Communication',
    baseName: 'Bharati Station',
    model: 'Cobham Sea Tel 9711 Radome',
    serialNumber: 'SAT-9711-COB',
    assignedPersonnelName: 'Sanjay Deshmukh',
    condition: 'Excellent',
    status: 'Operational',
    maintenanceStatus: 'Up to Date',
    nextMaintenanceDate: '2026-07-20T00:00:00.000Z',
    lastMaintenanceDate: '2026-01-15T00:00:00.000Z',
    maintenanceIntervalDays: 180,
    specifications: {
      dishDiameter: '2.4m Heated Carbon Fiber Dish',
      uplinkBand: 'C/Ku-band dual polar transceivers',
      trackingAccuracy: '0.1° in 60-knot winds',
    },
    maintenanceHistory: [],
  },
  {
    _id: '67cda5000000000000000005',
    assetCode: 'AST-0005',
    assetTag: 'AST-SCI-01',
    name: 'Electro-Thermal Ice Core Drill Mast Assembly',
    assetName: 'Electro-Thermal Ice Core Drill Mast Assembly',
    category: 'Scientific Instrument',
    baseName: 'Bharati Station',
    model: 'Hans Tausen 4-Inch Deep Corer',
    serialNumber: 'HT-COR-409',
    assignedPersonnelName: 'Dr. Rajesh Sharma',
    condition: 'Needs Repair',
    status: 'Standby',
    maintenanceStatus: 'Due Soon',
    nextMaintenanceDate: '2026-03-25T00:00:00.000Z',
    lastMaintenanceDate: '2025-12-20T00:00:00.000Z',
    maintenanceIntervalDays: 45,
    specifications: {
      maxDepth: '350 meters ice sheet extraction',
      coreDiameter: '98 mm pristine cores',
      mastTilt: 'Hydraulic winch tower with cable tension monitor',
    },
    maintenanceHistory: [],
  },
];


let mockPersonnel = [
  {
    _id: '67cda6000000000000000001',
    participantId: 'POL-0101',
    employeeId: 'POL-0101',
    name: 'Dr. Rajesh Sharma',
    designation: 'Lead Glaciologist & Science Director',
    role: 'Lead Glaciologist',
    rank: 'Principal Investigator',
    department: 'Science',
    team: 'Cryosphere Core Team',
    shift: 'Alpha (Day)',
    baseName: 'Bharati Station',
    currentBase: '67cda0000000000000000002',
    status: 'Deployed',
    medicalClearance: 'Cleared',
    bloodGroup: 'B+',
    email: 'r.sharma@polaris.aq',
    phone: '+91-9876543210',
    emergencyContact: {
      name: 'Ananya Sharma',
      phone: '+91-9876543210',
      relationship: 'Spouse',
    },
    skills: ['Deep Ice-Coring', 'Isotope Mass Spectrometry', 'Glacial Radar Profiling', 'Sub-Zero Survival'],
    certifications: ['Polar Survival V4', 'Cryo-Drilling Level 3', 'Wilderness First Aid'],
    movementHistory: [
      {
        _id: 'mh-01',
        event: 'Deployment',
        location: 'Larsemann Hills Sector 2',
        baseName: 'Bharati Station',
        timestamp: '2025-11-15T08:00:00.000Z',
        updatedBy: 'Commander Radhika Roy',
        notes: 'In-field deployment for Amery Ice Shelf drill survey',
      },
    ],
  },
  {
    _id: '67cda6000000000000000002',
    participantId: 'POL-0102',
    employeeId: 'POL-0102',
    name: 'Dr. Maya Patel',
    designation: 'Chief Expedition Medical Officer',
    role: 'Chief Medical Officer',
    rank: 'Senior Surgeon',
    department: 'Medical',
    team: 'Trauma & Life Support',
    shift: 'Continuous Watch',
    baseName: 'Bharati Station',
    currentBase: '67cda0000000000000000002',
    status: 'At Base',
    medicalClearance: 'Cleared',
    bloodGroup: 'O-',
    email: 'm.patel@polaris.aq',
    phone: '+91-9876543211',
    emergencyContact: {
      name: 'Karan Patel',
      phone: '+91-9876543211',
      relationship: 'Brother',
    },
    skills: ['Hypothermia Re-warming', 'Tele-Robotic Surgery', 'Frostbite Triage', 'Hyperbaric Medicine'],
    certifications: ['Advanced Trauma Life Support (ATLS)', 'Polar Medicine Fellow', 'Aeromedical Evacuation'],
    movementHistory: [
      {
        _id: 'mh-02',
        event: 'Check In',
        location: 'Bharati Station Trauma Suite',
        baseName: 'Bharati Station',
        timestamp: '2025-11-20T10:00:00.000Z',
        updatedBy: 'Dr. Rajesh Sharma',
        notes: 'Station medical quarantine station established',
      },
    ],
  },
  {
    _id: '67cda6000000000000000003',
    participantId: 'POL-0103',
    employeeId: 'POL-0103',
    name: 'Pooja Deshmukh',
    designation: 'Polar Air Fleet Logistics Director',
    role: 'Logistics Flight Director',
    rank: 'Flight Director',
    department: 'Logistics',
    team: 'Air Cargo Operations',
    shift: 'Charlie (Swing)',
    baseName: 'Maitri Station',
    currentBase: '67cda0000000000000000001',
    status: 'Active',
    medicalClearance: 'Cleared',
    bloodGroup: 'A+',
    email: 'p.deshmukh@polaris.aq',
    phone: '+91-9876543214',
    emergencyContact: {
      name: 'Vinod Deshmukh',
      phone: '+91-9876543214',
      relationship: 'Father',
    },
    skills: ['Ski-Plane Airdrop Routing', 'Sub-Zero Fuel Transfer', 'Cargo Manifest Authorization', 'Helicopter Sling Operations'],
    certifications: ['ICAO Polar Aviation Ops', 'Dangerous Goods Cryo Handling', 'Search & Rescue Coord'],
    movementHistory: [
      {
        _id: 'mh-03',
        event: 'Transfer',
        location: 'Cape Town Logistics Berth',
        baseName: 'Maitri Station',
        timestamp: '2026-01-05T14:30:00.000Z',
        updatedBy: 'Capt. Amitav Banerjee',
        notes: 'Transferred from maritime staging to Maitri airstrip',
      },
    ],
  },
  {
    _id: '67cda6000000000000000004',
    participantId: 'POL-0104',
    employeeId: 'POL-0104',
    name: 'Capt. Amitav Banerjee',
    designation: 'Maitri Station Base Commander',
    role: 'Station Base Commander',
    rank: 'Commander',
    department: 'Command',
    team: 'Station Directorate',
    shift: 'Alpha (Day)',
    baseName: 'Maitri Station',
    currentBase: '67cda0000000000000000001',
    status: 'At Base',
    medicalClearance: 'Cleared',
    bloodGroup: 'A-',
    email: 'a.banerjee@polaris.aq',
    phone: '+91-9876543215',
    emergencyContact: {
      name: 'Sharmila Banerjee',
      phone: '+91-9876543215',
      relationship: 'Spouse',
    },
    skills: ['Ice Navigation Command', 'Catastrophic Gale Protocol', 'Microgrid Contingency', 'Crisis Communications'],
    certifications: ['Master Mariner Unlimited (Polar Code)', 'Crisis Management Master', 'Antarctic Wintering V5'],
    movementHistory: [
      {
        _id: 'mh-04',
        event: 'Check In',
        location: 'Maitri Oasis Command Bridge',
        baseName: 'Maitri Station',
        timestamp: '2025-10-10T12:00:00.000Z',
        updatedBy: 'Commander Radhika Roy',
        notes: 'Assumed annual command for 44th expedition wintering team',
      },
    ],
  },
  {
    _id: '67cda6000000000000000005',
    participantId: 'POL-0105',
    employeeId: 'POL-0105',
    name: 'Vikram Sengupta',
    designation: 'Chief Electrical & Microgrid Engineer',
    role: 'Chief Electrical Engineer',
    rank: 'Chief Engineer',
    department: 'Operations',
    team: 'Energy & Life Support',
    shift: 'Bravo (Night)',
    baseName: 'Maitri Station',
    currentBase: '67cda0000000000000000001',
    status: 'Active',
    medicalClearance: 'Cleared',
    bloodGroup: 'O+',
    email: 'v.sengupta@polaris.aq',
    phone: '+91-9876543212',
    emergencyContact: {
      name: 'Rupali Sengupta',
      phone: '+91-9876543212',
      relationship: 'Spouse',
    },
    skills: ['Cold-Start Diesel Gensets', 'Heat-Trace Line Thawing', 'Battery Bank Balancing', 'SCADA Automation'],
    certifications: ['High-Voltage Arctic Certified', 'Caterpillar Marine Certified', 'Combustion Diagnostic Level 4'],
    movementHistory: [
      {
        _id: 'mh-05',
        event: 'Status Change',
        location: 'Generator Hangar 1',
        baseName: 'Maitri Station',
        timestamp: '2026-02-28T09:00:00.000Z',
        updatedBy: 'Capt. Amitav Banerjee',
        notes: 'Assigned to emergency maintenance on Generator #1',
      },
    ],
  },
  {
    _id: '67cda6000000000000000006',
    participantId: 'POL-0106',
    employeeId: 'POL-0106',
    name: 'Arjun Nair',
    designation: 'Senior Over-Ice Traverse Pilot & Mechanic',
    role: 'Traverse Master Mechanic',
    rank: 'Senior Specialist',
    department: 'Operations',
    team: 'Heavy Tracked Transport',
    shift: 'Alpha (Day)',
    baseName: 'Bharati Station',
    currentBase: '67cda0000000000000000002',
    status: 'Deployed',
    medicalClearance: 'Cleared',
    bloodGroup: 'B-',
    email: 'a.nair@polaris.aq',
    phone: '+91-9876543216',
    emergencyContact: {
      name: 'Deepa Nair',
      phone: '+91-9876543216',
      relationship: 'Sister',
    },
    skills: ['PistenBully 300 Track Overhaul', 'Crevasse Detection Radar', 'Winch Rescue Systems', 'Sub-Zero Hydraulics'],
    certifications: ['Kässbohrer Master Technician', 'Crevasse Rescue Lead', 'Extreme Cold Heavy Vehicle License'],
    movementHistory: [
      {
        _id: 'mh-06',
        event: 'Deployment',
        location: 'Prydz Bay Sea-Ice Corridor',
        baseName: 'Bharati Station',
        timestamp: '2026-03-01T06:00:00.000Z',
        updatedBy: 'Dr. Rajesh Sharma',
        notes: 'Piloting Kässbohrer sled convoy with cryo core samples',
      },
    ],
  },
  {
    _id: '67cda6000000000000000007',
    participantId: 'POL-0107',
    employeeId: 'POL-0107',
    name: 'Dr. Sunita Rao',
    designation: 'High-Latitude Atmospheric Physicist',
    role: 'Atmospheric Scientist',
    rank: 'Senior Scientist',
    department: 'Science',
    team: 'Zeppelin Aerosol Project',
    shift: 'Alpha (Day)',
    baseName: 'Himadri Station',
    currentBase: '67cda0000000000000000003',
    status: 'At Base',
    medicalClearance: 'Cleared',
    bloodGroup: 'AB+',
    email: 's.rao@polaris.aq',
    phone: '+91-9876543217',
    emergencyContact: {
      name: 'K. V. Rao',
      phone: '+91-9876543217',
      relationship: 'Father',
    },
    skills: ['Lidar Backscatter Inversion', 'Aerosol Mass Spectrometry', 'Ozone Column Calibration', 'Zeppelin Lab Feed'],
    certifications: ['Arctic Scientific Diver', 'Class 4 Laser Safety Officer', 'Polar Survival Svalbard V4'],
    movementHistory: [
      {
        _id: 'mh-07',
        event: 'Check In',
        location: 'Himadri Clean Air Pod',
        baseName: 'Himadri Station',
        timestamp: '2026-02-14T11:00:00.000Z',
        updatedBy: 'Devendra Pratap',
        notes: 'Initiated optical bench alignment for spring campaign',
      },
    ],
  },
  {
    _id: '67cda6000000000000000008',
    participantId: 'POL-0108',
    employeeId: 'POL-0108',
    name: 'Devendra Pratap',
    designation: 'Arctic Station Operations Lead',
    role: 'Station Operations Lead',
    rank: 'Station Lead',
    department: 'Command',
    team: 'Arctic Outpost Staff',
    shift: 'Continuous Watch',
    baseName: 'Himadri Station',
    currentBase: '67cda0000000000000000003',
    status: 'At Base',
    medicalClearance: 'Cleared',
    bloodGroup: 'A+',
    email: 'd.pratap@polaris.aq',
    phone: '+91-9876543218',
    emergencyContact: {
      name: 'Meera Pratap',
      phone: '+91-9876543218',
      relationship: 'Spouse',
    },
    skills: ['Polar Bear Defense Protocol', 'Ny-Ålesund Fjord Boating', 'Satellite Link Maintenance', 'Snowmobile Fleet Repair'],
    certifications: ['Norwegian Polar Bear Rifle Permit', 'Small Craft Polar Skipper', 'Arctic Survival Instructor'],
    movementHistory: [
      {
        _id: 'mh-08',
        event: 'Check In',
        location: 'Himadri Base Technical Annex',
        baseName: 'Himadri Station',
        timestamp: '2026-01-15T09:00:00.000Z',
        updatedBy: 'Commander Radhika Roy',
        notes: 'Overseeing winter-spring handover at 79°N',
      },
    ],
  },
  {
    _id: '67cda6000000000000000009',
    participantId: 'POL-0109',
    employeeId: 'POL-0109',
    name: 'Sanjay Deshmukh',
    designation: 'Senior Telemetry & SatCom Systems Engineer',
    role: 'SatCom Systems Engineer',
    rank: 'Lead Engineer',
    department: 'Engineering',
    team: 'Telecommunications & Uplink',
    shift: 'Alpha (Day)',
    baseName: 'Bharati Station',
    currentBase: '67cda0000000000000000002',
    status: 'Active',
    medicalClearance: 'Cleared',
    bloodGroup: 'O+',
    email: 's.deshmukh@polaris.aq',
    phone: '+91-9876543213',
    emergencyContact: {
      name: 'Neha Deshmukh',
      phone: '+91-9876543213',
      relationship: 'Spouse',
    },
    skills: ['Cobham Sea Tel Ka/C-Band', 'Iridium Certus Routing', 'Fiber Optic Cold Splice', 'Cybersecurity Cryptography'],
    certifications: ['Cisco CCNA Polar Networks', 'Cobham Marine Antennas L3', 'Crypto Officer Secret Clearance'],
    movementHistory: [
      {
        _id: 'mh-09',
        event: 'Return',
        location: 'Bharati Satellite Radome Bay',
        baseName: 'Bharati Station',
        timestamp: '2026-02-20T16:00:00.000Z',
        updatedBy: 'Dr. Rajesh Sharma',
        notes: 'Completed Ka-band radome heating coil test',
      },
    ],
  },
  {
    _id: '67cda6000000000000000010',
    participantId: 'POL-0110',
    employeeId: 'POL-0110',
    name: 'Priya Venkat',
    designation: 'Expedition Roster & HR Compliance Officer',
    role: 'Personnel Operations Officer',
    rank: 'Officer',
    department: 'Command',
    team: 'HQ Logistics & Roster',
    shift: 'Alpha (Day)',
    baseName: 'RV Bharati',
    currentBase: '67cda0000000000000000004',
    status: 'In Transit',
    medicalClearance: 'Cleared',
    bloodGroup: 'B+',
    email: 'p.venkat@polaris.aq',
    phone: '+91-9876543219',
    emergencyContact: {
      name: 'S. Venkat',
      phone: '+91-9876543219',
      relationship: 'Father',
    },
    skills: ['Polar Treaty Compliance', 'Crew Shift Scheduling', 'Psychological Health Tracking', 'Emergency Muster Auditing'],
    certifications: ['Antarctic Treaty Compliance Officer', 'SOLAS Marine Safety', 'Critical Incident Stress Mgmt'],
    movementHistory: [
      {
        _id: 'mh-10',
        event: 'Check In',
        location: 'RV Bharati Quarterdeck',
        baseName: 'RV Bharati',
        timestamp: '2026-03-02T13:00:00.000Z',
        updatedBy: 'Commander Radhika Roy',
        notes: 'Embarkation for mid-season rotation audit',
      },
    ],
  },
];

let mockTasks = [
  {
    _id: '67cda7000000000000000001',
    title: 'Emergency Generator Fuel Line Inspection',
    description: 'Check fuel lines for ice crystallization and verify heat trace tape is functioning on Generator #1.',
    priority: 'Critical',
    status: 'In Progress',
    deadline: '2026-09-14T12:00:00.000Z',
    dueDate: '2026-09-14T12:00:00.000Z',
    assignedTo: '67cda6000000000000000005',
    assignedToName: 'Vikram Sengupta',
    base: '67cda0000000000000000001',
    comments: [
      { authorName: 'Capt. Amitav Banerjee', text: 'Auxiliary line defrosted. Secondary inspection pending.', timestamp: new Date(Date.now() - 3600000 * 4) }
    ],
  },
  {
    _id: '67cda7000000000000000002',
    title: 'Quarterly Inventory Audit - Medical Cryo Vault',
    description: 'Verify all plasma units, anti-venom, and antibiotics batches against digital manifests.',
    priority: 'High',
    status: 'Overdue',
    deadline: '2026-09-10T00:00:00.000Z',
    dueDate: '2026-09-10T00:00:00.000Z',
    assignedTo: '67cda6000000000000000002',
    assignedToName: 'Dr. Maya Patel',
    base: '67cda0000000000000000002',
    comments: [
      { authorName: 'Dr. Maya Patel', text: 'Delayed due to triage duty during storm.', timestamp: new Date(Date.now() - 3600000 * 24) }
    ],
  },
  {
    _id: '67cda7000000000000000003',
    title: 'Crevasse Radar Calibration on PistenBully 300',
    description: 'Calibrate ground-penetrating radar antenna array prior to 120km deep field ice-shelf traverse.',
    priority: 'Critical',
    status: 'In Progress',
    deadline: '2026-09-16T18:00:00.000Z',
    dueDate: '2026-09-16T18:00:00.000Z',
    assignedTo: '67cda6000000000000000006',
    assignedToName: 'Arjun Nair',
    base: '67cda0000000000000000002',
    comments: [],
  },
  {
    _id: '67cda7000000000000000004',
    title: 'Satellite Uplink Ka-Band Feed Horn De-icing',
    description: 'Inspect radome heating element coils and ensure no ice damming obstructs telemetry beam to Intelsat.',
    priority: 'High',
    status: 'Pending',
    deadline: '2026-09-15T15:00:00.000Z',
    dueDate: '2026-09-15T15:00:00.000Z',
    assignedTo: '67cda6000000000000000009',
    assignedToName: 'Sanjay Deshmukh',
    base: '67cda0000000000000000002',
    comments: [],
  },
  {
    _id: '67cda7000000000000000005',
    title: 'Sub-Ice Coring Core Log Archive & Sealed Transport',
    description: 'Transfer 120m Amery core cylinders into liquid nitrogen vacuum container and sign chain of custody.',
    priority: 'Medium',
    status: 'Completed',
    deadline: '2026-09-11T00:00:00.000Z',
    dueDate: '2026-09-11T00:00:00.000Z',
    assignedTo: '67cda6000000000000000001',
    assignedToName: 'Dr. Rajesh Sharma',
    base: '67cda0000000000000000002',
    comments: [
      { authorName: 'Dr. Rajesh Sharma', text: 'All 4 sample cylinders cataloged and sealed at -82°C.', timestamp: new Date(Date.now() - 3600000 * 20) }
    ],
  },
  {
    _id: '67cda7000000000000000006',
    title: 'Aviation Fuel Bladder Leak Containment Protocol',
    description: 'Inspect secondary spill-berm liners around Jet A-1 storage bladders and pump any melted snow runoff.',
    priority: 'Critical',
    status: 'Pending',
    deadline: '2026-09-14T09:00:00.000Z',
    dueDate: '2026-09-14T09:00:00.000Z',
    assignedTo: '67cda6000000000000000003',
    assignedToName: 'Pooja Deshmukh',
    base: '67cda0000000000000000001',
    comments: [],
  },
  {
    _id: '67cda7000000000000000007',
    title: 'Zeppelin Aerosol Optical Bench Collimation',
    description: 'Realign high-latitude multi-wavelength LIDAR emitter mirror and verify zero backscatter distortion.',
    priority: 'Medium',
    status: 'In Progress',
    deadline: '2026-09-17T17:00:00.000Z',
    dueDate: '2026-09-17T17:00:00.000Z',
    assignedTo: '67cda6000000000000000007',
    assignedToName: 'Dr. Sunita Rao',
    base: '67cda0000000000000000003',
    comments: [],
  },
  {
    _id: '67cda7000000000000000008',
    title: 'Station Perimeter Survival Cache Inspection',
    description: 'Inspect food rations, sub-zero sleeping bags, and emergency radio transceivers in Outpost Pods Alpha & Beta.',
    priority: 'Low',
    status: 'Completed',
    deadline: '2026-09-08T00:00:00.000Z',
    dueDate: '2026-09-08T00:00:00.000Z',
    assignedTo: '67cda6000000000000000004',
    assignedToName: 'Capt. Amitav Banerjee',
    base: '67cda0000000000000000001',
    comments: [
      { authorName: 'Capt. Amitav Banerjee', text: 'Caches 1 and 2 replenished with emergency MREs and batteries.', timestamp: new Date(Date.now() - 3600000 * 48) }
    ],
  },
];

let mockIncidents = [
  {
    _id: '67cda8000000000000000001',
    incidentCode: 'INC-2026-001',
    title: 'Catastrophic Gale & Generator #1 Overheat Alarm',
    description: 'Sudden wind gusts of 68 knots accompanied by ambient -44°C temp caused turbine icing and tripped secondary generator at Maitri Station.',
    type: 'Facility',
    severity: 'Critical',
    status: 'Responding',
    baseName: 'Maitri Station',
    baseId: '67cda0000000000000000001',
    location: 'Maitri Power Module 2',
    reporterName: 'Commander Radhika Roy',
    requiredResources: ['CAT 3406 Alternator Spare', 'Heat Trace Wrap', 'Emergency Fuel Bladder'],
    assignedTeam: [
      { name: 'Vikram Sengupta', designation: 'Chief Electrical Engineer', role: 'Lead Responder' },
      { name: 'Capt. Amitav Banerjee', designation: 'Station Base Commander', role: 'Incident Commander' }
    ],
    dispatchDetails: {
      unit: 'Hägglunds Bv206 Polar Track Unit 1',
      leadResponder: 'Vikram Sengupta',
      dispatchedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      status: 'On Site (Mitigating)',
      eta: 'Arrived',
    },
    actions: [
      { description: 'Switched living quarters to Emergency Battery Array', performedBy: 'Capt. Amitav Banerjee', timestamp: new Date(Date.now() - 50 * 60 * 1000) },
      { description: 'Isolated Auxiliary Diesel Unit #2 for manual bypass', performedBy: 'Vikram Sengupta', timestamp: new Date(Date.now() - 25 * 60 * 1000) },
      { description: 'Emergency engineering response team deployed via Hägglunds tracked sled', performedBy: 'Commander Radhika Roy', timestamp: new Date(Date.now() - 15 * 60 * 1000) }
    ],
    timeline: [
      { status: 'Reported', note: 'Emergency signal received from Maitri Power SCADA', actorName: 'Commander Radhika Roy', timestamp: new Date(Date.now() - 55 * 60 * 1000) },
      { status: 'Assessing', note: 'Thermal runaway confirmed on secondary coils', actorName: 'Vikram Sengupta', timestamp: new Date(Date.now() - 45 * 60 * 1000) },
      { status: 'Responding', note: 'SOS Dispatch Confirmed: Bv206 response team rolling with heat trace kits', actorName: 'Commander Radhika Roy', timestamp: new Date(Date.now() - 20 * 60 * 1000) },
    ]
  },
  {
    _id: '67cda8000000000000000002',
    incidentCode: 'INC-2026-002',
    title: 'Crevasse Fall & Acute Hypothermia Alert - Prydz Bay Traverse',
    description: 'Snowcat scout vehicle slipped into bridged transverse crevasse 18 km north-west of Bharati. 2 personnel require immediate deep-core trauma extraction.',
    type: 'Medical',
    severity: 'Critical',
    status: 'Responding',
    baseName: 'Bharati Station',
    baseId: '67cda0000000000000000002',
    location: 'Prydz Bay Sector 4 (Lat -68.82°, Lng 74.55°)',
    reporterName: 'Dr. Rajesh Sharma',
    requiredResources: ['Hyperbaric Trauma Pod', 'Mi-8 Rescue Helo', 'Crevasse Winch Rig', 'O-Neg Blood Plasma'],
    assignedTeam: [
      { name: 'Dr. Maya Patel', designation: 'Chief Medical Officer', role: 'Medical Flight Director' },
      { name: 'Arjun Nair', designation: 'Traverse Master Mechanic', role: 'Heavy Winch Specialist' }
    ],
    dispatchDetails: {
      unit: 'Mil Mi-8 Polar Medevac Helo Flight-01',
      leadResponder: 'Dr. Maya Patel',
      dispatchedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      status: 'Airborne En Route',
      eta: '10 Minutes',
    },
    actions: [
      { description: 'Received emergency beacon transmission on 406 MHz Cospas-Sarsat', performedBy: 'Sanjay Deshmukh', timestamp: new Date(Date.now() - 35 * 60 * 1000) },
      { description: 'Scrambled Mi-8 Medevac helicopter with trauma life-support gear', performedBy: 'Commander Radhika Roy', timestamp: new Date(Date.now() - 20 * 60 * 1000) },
      { description: 'Primary crevasse winch rig pre-staged on Bharati helideck', performedBy: 'Arjun Nair', timestamp: new Date(Date.now() - 10 * 60 * 1000) }
    ],
    timeline: [
      { status: 'Reported', note: 'Mayday received from Traverse unit Charlie', actorName: 'Dr. Rajesh Sharma', timestamp: new Date(Date.now() - 40 * 60 * 1000) },
      { status: 'Assessing', note: 'Crevasse depth estimated at 14 meters. Telemetry shows stable vitals.', actorName: 'Dr. Maya Patel', timestamp: new Date(Date.now() - 28 * 60 * 1000) },
      { status: 'Responding', note: 'Tactical SOS Medevac dispatch airborne', actorName: 'Commander Radhika Roy', timestamp: new Date(Date.now() - 20 * 60 * 1000) },
    ]
  },
  {
    _id: '67cda8000000000000000003',
    incidentCode: 'INC-2026-003',
    title: 'Extreme Blizzard Cat-4 Whiteout & Convoy Halt',
    description: 'Sustained 74-knot katabatic winds causing zero-meter visibility along coastal supply route. Convoy CRG-2026-002 anchored in place.',
    type: 'Weather',
    severity: 'High',
    status: 'Active',
    baseName: 'Bharati Station',
    baseId: '67cda0000000000000000002',
    location: 'Cape Darnley Transit Corridor',
    reporterName: 'Pooja Deshmukh',
    requiredResources: ['Emergency Arctic Hab Pod', 'Heated Fuel Bladder', 'Iridium Satellite Beacon'],
    assignedTeam: [
      { name: 'Pooja Deshmukh', designation: 'Logistics Flight Director', role: 'Convoy Lead' }
    ],
    dispatchDetails: {
      unit: 'Shelter Pod Array Beta',
      leadResponder: 'Pooja Deshmukh',
      dispatchedAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
      status: 'Halted in Protective Formation',
      eta: 'Sheltered',
    },
    actions: [
      { description: 'Convoy formed defensive circular windbreak against 74-knot gusts', performedBy: 'Pooja Deshmukh', timestamp: new Date(Date.now() - 100 * 60 * 1000) },
      { description: 'Continuous Iridium Certus heartbeat broadcast established', performedBy: 'Sanjay Deshmukh', timestamp: new Date(Date.now() - 60 * 60 * 1000) }
    ],
    timeline: [
      { status: 'Reported', note: 'Barometric drop of 24 hPa in 2 hours', actorName: 'Pooja Deshmukh', timestamp: new Date(Date.now() - 120 * 60 * 1000) },
      { status: 'Active', note: 'Sheltered in place awaiting gale moderation', actorName: 'Commander Radhika Roy', timestamp: new Date(Date.now() - 90 * 60 * 1000) }
    ]
  },
  {
    _id: '67cda8000000000000000004',
    incidentCode: 'INC-2026-004',
    title: 'Ny-Ålesund Atmospheric Lidar Radome Thermal Breaker Trip',
    description: 'Ice accumulation on external optical dome tripped heating loop. Laser optics shut down to prevent thermal shock.',
    type: 'Equipment Failure',
    severity: 'Medium',
    status: 'Resolved',
    baseName: 'Himadri Station',
    baseId: '67cda0000000000000000003',
    location: 'Zeppelin Observatory Optical Annex',
    reporterName: 'Devendra Pratap',
    requiredResources: ['Silicone Heat Elements', 'Optical Cleaning Kit'],
    assignedTeam: [
      { name: 'Dr. Sunita Rao', designation: 'Atmospheric Scientist', role: 'Laser Specialist' },
      { name: 'Devendra Pratap', designation: 'Station Operations Lead', role: 'Lead Technician' }
    ],
    dispatchDetails: {
      unit: 'Station Technical Maintenance Squad',
      leadResponder: 'Devendra Pratap',
      dispatchedAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
      status: 'Completed & Certified',
      eta: 'Finished',
    },
    actions: [
      { description: 'Manually bypassed secondary circuit and melted dome perimeter ice', performedBy: 'Devendra Pratap', timestamp: new Date(Date.now() - 180 * 60 * 1000) },
      { description: 'Laser optics recalibrated and realigned with satellite benchmark', performedBy: 'Dr. Sunita Rao', timestamp: new Date(Date.now() - 120 * 60 * 1000) }
    ],
    timeline: [
      { status: 'Reported', note: 'Lidar telemetry interlock triggered', actorName: 'Devendra Pratap', timestamp: new Date(Date.now() - 250 * 60 * 1000) },
      { status: 'Responding', note: 'Technicians on roof inspecting optical dome', actorName: 'Dr. Sunita Rao', timestamp: new Date(Date.now() - 200 * 60 * 1000) },
      { status: 'Resolved', note: 'Thermal balance restored. Optical bench nominal.', actorName: 'Devendra Pratap', timestamp: new Date(Date.now() - 110 * 60 * 1000) }
    ]
  }
];

let mockAlerts = [
  {
    _id: '67cda9000000000000000001',
    title: 'CRITICAL: Severe Generator Fault at Maitri Station',
    message: 'Station Prime Generator #1 is in Maintenance mode during severe winter gale. Immediate auxiliary power check required.',
    type: 'Emergency',
    severity: 'Critical',
    module: 'Incidents',
    base: 'Maitri Station',
    isRead: false,
    status: 'Active',
    telemetry: { temp: '-44°C', windSpeed: '68 kt', coreTemp: '94°C', auxiliaryPwr: 'Active (Backup 2)' },
    createdAt: new Date(Date.now() - 1000 * 60 * 12),
  },
  {
    _id: '67cda9000000000000000002',
    title: 'LOW STOCK: Aviation Turbine Fuel below threshold',
    message: 'Maitri Station Jet A-1 Fuel is at 2,400L (Minimum threshold: 5,000L). Convoy CRG-2026-001 currently in transit.',
    type: 'LowStock',
    severity: 'High',
    module: 'Inventory',
    base: 'Maitri Station',
    isRead: false,
    status: 'Active',
    telemetry: { currentLiters: '2,400 L', minThreshold: '5,000 L', resupplyETA: '14 Hours' },
    createdAt: new Date(Date.now() - 1000 * 60 * 45),
  },
  {
    _id: '67cda9000000000000000003',
    title: 'DELAYED: Cargo CRG-2026-002 Grounded at Cape Darnley',
    message: 'Replacement Generator Crankshaft cargo grounded at Cape Darnley due to 65-knot gale winds.',
    type: 'CargoDelay',
    severity: 'High',
    module: 'Cargo',
    base: 'Bharati Station',
    isRead: false,
    status: 'Active',
    telemetry: { route: 'Cape Darnley -> Bharati', delayTime: '+36 Hours', convoyState: 'Halted' },
    createdAt: new Date(Date.now() - 1000 * 60 * 95),
  },
  {
    _id: '67cda9000000000000000004',
    title: 'WEATHER ALERT: Blizzard Cat 3 approaching Larsemann Hills',
    message: 'Extreme wind (74 kt gusts) causing whiteout conditions. LARSEM-2026 expedition sheltered in place.',
    type: 'Weather',
    severity: 'Critical',
    module: 'Expeditions',
    base: 'Bharati Station',
    isRead: false,
    status: 'Active',
    telemetry: { windGust: '74 kt', visibility: '< 50m', barometricPressure: '962 hPa' },
    createdAt: new Date(Date.now() - 1000 * 60 * 150),
  },
  {
    _id: '67cda9000000000000000005',
    title: 'WARNING: Ny-Ålesund Satellite Uplink Attenuation',
    message: 'Atmospheric ion disturbance detected over Spitsbergen. Uplink packet jitter elevated to 142ms.',
    type: 'System',
    severity: 'Warning',
    module: 'System',
    base: 'Himadri Station',
    isRead: false,
    status: 'Active',
    telemetry: { latency: '142 ms', signalStrength: '68%', carrier: 'Iridium Certus 700' },
    createdAt: new Date(Date.now() - 1000 * 60 * 210),
  },
  {
    _id: '67cda9000000000000000006',
    title: 'WARNING: Marine Ice Accretion on RV Bharati Port Bow',
    message: 'Spray freezing rate elevated in sector 4. Automatic de-icing thermal coils engaged.',
    type: 'Maintenance',
    severity: 'Warning',
    module: 'Assets',
    base: 'RV Bharati',
    isRead: true,
    status: 'Active',
    telemetry: { seaTemp: '-1.8°C', iceThickness: '4.2 cm', thermalGrid: 'Nominal' },
    createdAt: new Date(Date.now() - 1000 * 60 * 320),
  },
];

const initMockDataFromCSV = async () => {
  return new Promise((resolve, reject) => {
    const csvPath = path.resolve(__dirname, '../../../../polaris_cargo_delay.csv');
    if (!fs.existsSync(csvPath)) {
      console.log('[Sync] CSV not found, using static mock data.');
      return resolve();
    }
    
    // Clear out some existing mock arrays
    mockExpeditions.length = 0;
    mockCargo.length = 0;
    mockAlerts.length = 0;
    mockIncidents.length = 0;
    
    let lineCount = 0;
    const rl = readline.createInterface({
      input: fs.createReadStream(csvPath),
      crlfDelay: Infinity
    });
    
    rl.on('line', (line) => {
      lineCount++;
      if (lineCount === 1) return; // skip header
      if (lineCount > 500) return; // Only parse top 500 to keep it manageable in memory for mocks
      
      const parts = line.split(',');
      if (parts.length < 15) return;
      
      // date,shipping_mode,order_region,market,category,quantity,sales,scheduled_days,max_temp_c,min_temp_c,precip_mm,ice_extent,weather_severity,ice_severity,delayed
      const [date, shippingMode, orderRegion, market, category, quantity, sales, scheduledDays, maxTemp, minTemp, precip, iceExtent, weatherSev, iceSev, delayed] = parts;
      
      const isDelayed = delayed === '1';
      const riskLevel = weatherSev === 'High' || iceSev === 'High' ? 'Critical' : weatherSev === 'Medium' ? 'Moderate' : 'Low';
      const readiness = isDelayed ? Math.floor(Math.random() * 40 + 20) : Math.floor(Math.random() * 20 + 80);
      
      // Expeditions
      if (lineCount % 15 === 0) {
        mockExpeditions.push({
          _id: '67cda200000' + lineCount.toString().padStart(13, '0'),
          code: `${orderRegion.substring(0,3).toUpperCase()}-${lineCount}`,
          name: `${market} ${category} Survey`,
          baseName: lineCount % 2 === 0 ? 'Maitri Station' : 'Bharati Station',
          status: isDelayed ? 'Active' : 'Completed',
          startDate: new Date(date),
          endDate: new Date(new Date(date).getTime() + parseInt(scheduledDays) * 86400000),
          readinessScore: readiness,
          riskLevel: riskLevel,
          objectives: [`Survey ${category} impact in ${orderRegion}`],
          milestones: [{ title: 'Deployment', dueDate: date, status: 'Completed' }],
          budget: { allocated: parseInt(sales) * 10, spent: parseInt(sales) * 5 },
          personnel: [{},{},{},{}], // Add some dummy personnel
          progress: isDelayed ? Math.floor(Math.random() * 40) : 100
        });
      }
      
      // Cargo
      if (lineCount % 10 === 0) {
        mockCargo.push({
          _id: '67cda300000' + lineCount.toString().padStart(13, '0'),
          trackingNumber: `CRG-2026-${lineCount}`,
          title: `${category} Resupply - ${orderRegion}`,
          category: category,
          priority: riskLevel === 'Critical' ? 'Urgent' : 'High',
          status: isDelayed ? 'Delayed' : 'InTransit',
          weightKg: parseInt(quantity) * 100,
          items: [{ name: category + ' Crate', quantity: parseInt(quantity), unit: 'Crates' }],
          shippingMode: shippingMode
        });
      }
      
      // Alerts
      if (isDelayed && riskLevel === 'Critical') {
        mockAlerts.push({
          _id: '67cda900000' + lineCount.toString().padStart(13, '0'),
          title: `${weatherSev} Weather Alert in ${orderRegion}`,
          message: `Severe conditions reported: Max Temp ${maxTemp}°C, ${precip}mm precip. ${category} cargo delayed.`,
          type: 'Weather',
          severity: 'Critical',
          module: 'Expeditions',
          isRead: false,
          createdAt: new Date(date),
        });
      }
      
    });
    
    rl.on('close', () => {
      console.log(`[Sync] Demo data synchronized from CSV. Loaded ${mockExpeditions.length} expeditions, ${mockCargo.length} cargo items, ${mockAlerts.length} alerts.`);
      resolve();
    });
  });
};

module.exports = {
  mockBases,
  mockUsers,
  mockExpeditions,
  mockCargo,
  mockInventory,
  mockAssets,
  mockPersonnel,
  mockTasks,
  mockIncidents,
  mockAlerts,
  initMockDataFromCSV
};
